### ISSUE TITLE
Cannot read property 'map' of undefined calling the ls function using SFTP Protocol

### ISSUE THREAD

**Issue by yus4u** [qusly/qusly-core#4]
when I call ls function using the SFTP protocol there is no check when the call get an error.

line 301 in file Client.js
`if (this._isSFTP) {
    return new Promise((resolve) => {
        this._sftpClient.readdir(path, (err, files) => {
            resolve(utils_1.getResponseData(err, {
                files: files.map(file => file_1.formatFile(basic_ftp_1.parseList(file.longname)[0]))
            }));
        });
    });
}`        

fix version
`if (this._isSFTP) {
    return new Promise((resolve) => {
        this._sftpClient.readdir(path, (err, files) => {
            if(err){
                resolve(utils_1.getResponseData(err));
            }else{
                resolve(utils_1.getResponseData(err, {
                    files: files.map(file => file_1.formatFile(basic_ftp_1.parseList(file.longname)[0]))
                }));
            }
        });
    });
}`

otherwise, we have this error:

`Uncaught TypeError: Cannot read property 'map' of undefined
      at _sftpClient.readdir (api/node_modules/qusly-core/build/models/client.js:306:42)
      at reread (api/node_modules/ssh2-streams/lib/sftp.js:1608:16)
      at SFTPStream._transform (api/node_modules/ssh2-streams/lib/sftp.js:417:17)
      at SFTPStream.Transform._read (_stream_transform.js:186:10)
      at SFTPStream._read (api/node_modules/ssh2-streams/lib/sftp.js:183:15)
      at SFTPStream.Transform._write (_stream_transform.js:174:12)
      at doWrite (_stream_writable.js:397:12)
      at writeOrBuffer (_stream_writable.js:383:5)
      at SFTPStream.Writable.write (_stream_writable.js:290:11)
      at Channel.ondata (_stream_readable.js:639:20)
      at addChunk (_stream_readable.js:263:12)
      at readableAddChunk (_stream_readable.js:250:11)
      at Channel.Readable.push (_stream_readable.js:208:10)
      at SSH2Stream.<anonymous> (api/node_modules/ssh2/lib/Channel.js:167:15)
      at parsePacket (api/node_modules/ssh2-streams/lib/ssh.js:3248:10)
      at SSH2Stream._transform (api/node_modules/ssh2-streams/lib/ssh.js:694:13)
      at SSH2Stream.Transform._read (_stream_transform.js:186:10)
      at SSH2Stream._read (api/node_modules/ssh2-streams/lib/ssh.js:253:15)
      at SSH2Stream.Transform._write (_stream_transform.js:174:12)
      at doWrite (_stream_writable.js:397:12)
      at writeOrBuffer (_stream_writable.js:383:5)
      at SSH2Stream.Writable.write (_stream_writable.js:290:11)
      at Socket.ondata (_stream_readable.js:639:20)
      at addChunk (_stream_readable.js:263:12)
      at readableAddChunk (_stream_readable.js:250:11)
      at Socket.Readable.push (_stream_readable.js:208:10)
      at TCP.onread (net.js:597:20)
`

**Comment by xnerhu** [comment]
Thanks for your issue. It's already fixed in the upcoming `1.1.0`. See [`this`](https://github.com/qusly/qusly-core/blob/master/src/models/sftp-client.ts#L137).
